apiVersion: v1
kind: Service
metadata:
  name: horme
  labels:
    app: horme
    component: microservice
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: horme
  sessionAffinity: None
  type: LoadBalancer