apiVersion: v1
data:
  .dockerconfigjson:
kind: Secret
metadata:
  creationTimestamp: "2022-02-24T12:58:53Z"
  name: regsecret
  namespace: default
  resourceVersion: "3424318"
  uid: c055d3c4-95be-4d28-8078-bc31316c9552
type: kubernetes.io/dockerconfigjson